[tool.poetry]
name = "krr-system"
version = "0.1.0"
description = ""
authors = ["beljasiak <Bartusus112309>"]
readme = "README.md"
packages = [{include = "krr_system"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
